"""empty message

Revision ID: 3e91f707fae3
Revises: f46723876628
Create Date: 2022-10-13 00:45:57.671529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e91f707fae3'
down_revision = 'f46723876628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=480), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
